[package]
name = "pixel_engine"
version = "0.1.0"
authors = ["johannst <johannes.stoelp@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/johannst/pixel_engine.git"

[dependencies]
lazy_static = "1.*"
